### ISSUE TITLE
Unable to install flipRegression on Windows

### ISSUE THREAD

**Issue by ememchichak** [Displayr/flipRegression#84]
Hello

R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.8.4    compiler_4.4.0    R6_2.5.1          cli_3.6.2         tools_4.4.0      
 [6] rstudioapi_0.16.0 curl_5.2.1        remotes_2.5.0     desc_1.4.3        callr_3.7.6      
[11] ps_1.7.6          pkgbuild_1.4.4  

I updated R, R Studio and R Tools yesterday (and RStudio again today as a new version came overnight), and just can't install the flipRegression package. I had it installed before (few R updates earlier) and had been using it normally. The error I get in the end is:

ERROR: compilation failed for package 'flipRegression'
* removing 'C:/Users/xxx/AppData/Local/R/win-library/4.4/flipRegression'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/xxx/AppData/Local/Temp/RtmpG4J6dT/file223c24f467b/flipRegression_1.3.63.tar.gz’ had non-zero exit status

I tried installation with:
remotes::install_github("Displayr/flipRegression") #this one worked last time
remotes::install_github("Displayr/flipRegression", dependencies = NA)
remotes::install_github("Displayr/flipRegression", build = FALSE, force=TRUE)

but get the same error in the end. Am I doing something wrong or how can i install it?

Maja

**Comment by jrwishart** [comment]
I just checked, I think the issue is `flipRegregression` is incompatible with the latest `RcppEigen`. It works for me if you downgrade `RcppEigen` to version `0.3.3.9.4`. Can you please try installing the earlier `RcppEigen` with 
```
remotes::install_github("CRAN/RcppEigen@0.3.3.9.4")
```
Then attempt to install `flipRegression` and it'll work. I'll look into updating the `DESCRIPTION` file to reflect this incompatibility asap and then look into updating `flipRegression` to work with the later `Eigen` library later.

**Comment by jrwishart** [comment]
The install will give proper feedback about the incompability once  https://github.com/Displayr/flipRegression/pull/85 is merged

**Comment by ememchichak** [comment]
Tyvm! Works fine now!
